version: "3"
services:
  app:
    container_name: app-container
    build: ./app-image
    image: app-image
    restart: always
    environment:
      - DB_HOST=json-server
    ports:
      - "4001:4001"
  json-server:
    container_name: json-server-container
    build: ./json-server-image
    image: json-server-image
    ports:
      - "3333:3333"
    volumes:
      - ./db/db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0 -p 3333
  django-app:
    build: ./django-app
    command: python manage.py runserver 0.0.0.0:1000
    ports:
      - "1000:1000"
  appvue:
    hostname: appvue
    build: ./appvue
    ports:
      - "80:80"